# é”šç‚¹
yt: &yt {type: select, proxies: [ğŸ”® èŠ‚ç‚¹å‡è¡¡,ğŸš æ²¹ç®¡èŠ‚ç‚¹, ğŸ”¯ èŠ‚ç‚¹æ•…è½¬, â™»ï¸ èŠ‚ç‚¹è‡ªåŠ¨, ğŸ§šæ‰‹åŠ¨èŠ‚ç‚¹]}
zj: &zj {type: select, include-all: true, filter: "(?i)(xxxx1)"}
zj1: &zj1 {type: select, include-all: true, filter: "(?i)(xxxx4)"}

filterUs: &filterUs {include-all: true, filter: "(?i)(xxxx2)"}
filterZJ: &filterZJ {include-all: true, filter: "^(?i)(xxxx3)"}


# è®¢é˜…ï¼Œåç§°ä¸èƒ½é‡å¤
proxy-providers:
  Airport_01:
    type: http
    interval: 14400 #4å°æ—¶ä¸€æ¬¡
    health-check:
      enable: true
      url: http://cp.cloudflare.com/
      #url: http://www.msftconnecttest.com/connecttest.txt      
      #url: https://www.apple.com/library/test/success.html
      #url: https://www.qualcomm.cn/generate_204	
      #url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ğŸŸ¢ ç›´è¿
    url: https://xxxx.com  
# ç”¨äºä¸‹è½½è®¢é˜…æ—¶æŒ‡å®šUA
global-ua:
    
# å…¨å±€é…ç½®
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
# interface-name: eth0  ï¼ˆè·¯ç”±å™¨ä¸‹æ ¹æ®æƒ…å†µæŒ‡å®šå‡ºç«™æ¥å£ï¼‰
#authentication:
  
#è€ƒè™‘rulesetçš„mrsæ¯”geodataæŸ¥è¯¢æ•ˆç‡è¦é«˜ï¼Œç›®å‰å·²æ›¿ä»£geodataæŸ¥è¯¢
#geoip ä½¿ç”¨æ–‡ä»¶ï¼Œmmdb æˆ–è€… datï¼Œå¯é€‰ true/false,trueä¸º dat
geodata-mode: true
# GEO æ–‡ä»¶åŠ è½½æ¨¡å¼ï¼ˆstandardï¼šæ ‡å‡†åŠ è½½å™¨/memconservativeï¼šä¸“ä¸ºå†…å­˜å—é™ (å°å†…å­˜) è®¾å¤‡ä¼˜åŒ–çš„åŠ è½½å™¨ (é»˜è®¤å€¼)ï¼‰
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 48
geox-url:
  geosite: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb"
  geoip: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  asn: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
  
# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090
secret: "123123"
external-ui: ui
external-ui-url: "https://ghfast.top/https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"

# åŒ¹é…è¿›ç¨‹ always/strict/off
find-process-mode: off
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

# ç­–ç•¥ç»„é€‰æ‹©å’Œfakeipç¼“å­˜
profile:
  store-selected: true
  store-fake-ip: true
#hosts:
  #base-v4v6-cm-miguvideo.e.cdn.chinamobile.com: studentlive.migucloud.com

# æµé‡å—…æ¢ï¼Œé»˜è®¤æƒ…å†µä¸‹ï¼Œsniffer åªå¯¹æ— åŸŸåçš„ IP è¯·æ±‚è¿›è¡Œå—…æ¢ï¼›force-domain å’Œ skip-domainé’ˆå¯¹ç‰¹æ®Šåœºæ™¯
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com" 
    
# ä»£ç†æ¨¡å¼
tun:
  enable: true
  stack: mixed
  mtu: 9000
  # dnsåŠ«æŒ
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  # è‡ªåŠ¨è®¾ç½®å…¨å±€è·¯ç”±ï¼Œå¯ä»¥è‡ªåŠ¨å°†å…¨å±€æµé‡è·¯ç”±è¿›å…¥ tun ç½‘å¡
  auto-route: true
  auto-redirect: true
  # è‡ªåŠ¨é€‰æ‹©æµé‡å‡ºå£æ¥å£
  auto-detect-interface: true
  
# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  #éµå¾ªåˆ†æµè§„åˆ™,å¼ºçƒˆä¸å»ºè®®å’Œ prefer-h3 ä¸€èµ·ä½¿ç”¨
  respect-rules: true
  # æ¨¡å¼åˆ‡æ¢ redir-host / fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  # æ¨¡å¼åˆ‡æ¢ whitelist/blacklist 
  # é»‘åå•æ¨¡å¼è¡¨ç¤ºå¦‚æœåŒ¹é…æˆåŠŸåˆ™ä¸è¿”å› Fake-IP, ç™½åå•æ¨¡å¼æ—¶åªæœ‰åŒ¹é…æˆåŠŸæ‰è¿”å› Fake-IP
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    #åŠ *å°±è¡¨ç¤ºæ‰€æœ‰éƒ½åœ¨é»‘åå•ï¼Œä¹Ÿå°±æ˜¯å˜æˆredir-host
    #- "*"
    - "+.lan"
    - "+.local"
    - RULE-SET:private_domain    
    - RULE-SET:cn_domain
    - RULE-SET:connectivity-check
    #DDNS
    - RULE-SET:mdirect
    #GOOGLE TV å¯¹æ—¶
    - aliyun.com  
  # ç”¨äºè§£æ DNS æœåŠ¡å™¨ çš„åŸŸå
  default-nameserver:    
    - 223.5.5.5
    - 119.29.29.29
  #æŒ‡å®šåŸŸåæŸ¥è¯¢çš„è§£ææœåŠ¡å™¨ï¼Œå› ä¸ºfallbake ipè¿‡æ»¤åŸŸåç¼ºçœä½¿ç”¨ nameserver è§£æï¼Œæ‰€ä»¥å¯¹ç›´è¿åŸŸåè¦æŒ‡å®šå›½å†…DNS
  nameserver-policy:    
    "RULE-SET:cn_domain,private_domain,mdirect,connectivity-check":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query     
  #é»˜è®¤çš„åŸŸåè§£ææœåŠ¡å™¨
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query    
  #ä»£ç†èŠ‚ç‚¹åŸŸåè§£ææœåŠ¡å™¨,å¼€å¯éµå¾ªåˆ†æµè§„åˆ™åï¼Œåˆ™å¿…é¡»åŠ è¿™ä¸€é¡¹
  proxy-server-nameserver:    
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query   
  #ç›´è¿çš„åŸŸåè§£ææœåŠ¡å™¨
  direct-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query     
proxies:
- name: "ğŸŸ¢ ç›´è¿"
  type: direct
  udp: true

# ğŸƒ ğŸŒˆ  ğŸ”´ğŸ•ºğŸ¿ğŸ’¸ğŸ® ğŸ‡­ğŸ‡° ğŸ‡¯ğŸ‡µ ğŸ”® ğŸš è‡ªå»º ğŸ§š ğŸ¥ ğŸ¦ ğŸ¬ ğŸ ğŸ“º ğŸ¶ ğŸ‘¨â€ğŸ’» ğŸ“¢ â“‚ï¸ âœˆï¸ ğŸ›©ï¸ ğŸ“½ï¸ ğŸ—ï¸ 
# ç­–ç•¥ç»„
proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ èŠ‚ç‚¹è‡ªåŠ¨, ğŸš è‡ªå»ºèŠ‚ç‚¹, ğŸ§šæ‰‹åŠ¨èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸš æ²¹ç®¡èŠ‚ç‚¹, <<: *zj}
  - {name: ğŸ“¹ YouTube, <<: *yt}
  - {name: ğŸ‡¬ è°·æ­ŒæœåŠ¡, <<: *zj}
  - {name: ğŸ¤– Ai_!cn, <<: *zj}
  - {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub, <<: *zj}
  - {name: ğŸªŸ Microsoft, <<: *zj1}
  - {name: ğŸ Apple, <<: *zj1}
  - {name: ğŸµ TikTok, <<: *zj}
  - {name: ğŸ“² Telegram, <<: *zj}
  - {name: ğŸ§‹ Twitter, <<: *zj}
  - {name: ğŸ•º TvProxy, <<: *zj}
  - {name: âœˆï¸ Speedtest, <<: *zj}
  - {name: ğŸ¥ NETFLIX, <<: *zj}  
  - {name: ğŸ’¶ PayPal, <<: *zj}
  - {name: ğŸŒˆ PrProxy, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸš è‡ªå»ºèŠ‚ç‚¹, â™»ï¸ èŠ‚ç‚¹è‡ªåŠ¨, ğŸ”¯ èŠ‚ç‚¹æ•…è½¬,ğŸ§šæ‰‹åŠ¨èŠ‚ç‚¹,ğŸ‡¬ è°·æ­ŒæœåŠ¡]}    
  
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [ğŸŸ¢ ç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸš è‡ªå»ºèŠ‚ç‚¹, â™»ï¸ èŠ‚ç‚¹è‡ªåŠ¨, ğŸ”¯ èŠ‚ç‚¹æ•…è½¬,ğŸ‡¬ è°·æ­ŒæœåŠ¡, ğŸŸ¢ ç›´è¿]}  
  - {name: ğŸš è‡ªå»ºèŠ‚ç‚¹, type: select, <<: *filterZJ}    
  - {name: ğŸ§šæ‰‹åŠ¨èŠ‚ç‚¹, type: select, <<: *filterUs} 
  - {name: ğŸ”¯ èŠ‚ç‚¹æ•…è½¬, type: fallback,tolerance: 20, interval: 300, <<: *filterUs}  
  - {name: â™»ï¸ èŠ‚ç‚¹è‡ªåŠ¨, type: url-test,tolerance: 20, interval: 300, <<: *filterUs}     
  - {name: ğŸ”® èŠ‚ç‚¹å‡è¡¡, type: load-balance, interval: 300, strategy: round-robin, <<: *filterUs}  
  - {name: ğŸŒ å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true}
rules:
  # è‹¥éœ€ç¦ç”¨ QUIC è¯·å–æ¶ˆæ³¨é‡Š QUIC ä¸¤æ¡è§„åˆ™
  # é˜²æ­¢ YouTube ç­‰ä½¿ç”¨ QUIC å¯¼è‡´é€Ÿåº¦ä¸ä½³, ç¦ç”¨ 443 ç«¯å£ UDP æµé‡ï¼ˆä¸åŒ…æ‹¬å›½å†…ï¼‰
  #- AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((RULE-SET,cn_ip))),REJECT
  #- AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((RULE-SET,cn_domain))),REJECT  
  #ç¦ç”¨æ‰€æœ‰UDPæµé‡
  - AND,((AND,(DST-PORT,443),(NETWORK,UDP))),REJECT
  - DOMAIN-SUFFIX,googleapis.cn,ğŸŸ¢ ç›´è¿
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,ğŸŸ¢ ç›´è¿  
  - RULE-SET,mdirect,ğŸŸ¢ ç›´è¿
  - RULE-SET,tvproxy,ğŸ•º TvProxy
  #mobi  
  #mm#- PROCESS-NAME,app.revanced.android.gms,ğŸ“¹ YouTube
  #mm#- PROCESS-NAME,app.rvx.android.youtube,ğŸ“¹ YouTube
  #mm#- PROCESS-NAME-REGEX,(?i)google,ğŸ‡¬ è°·æ­ŒæœåŠ¡ 
  #mm#- PROCESS-NAME-REGEX,.*downloads,ğŸ‡¬ è°·æ­ŒæœåŠ¡
  #mm#- PROCESS-NAME-REGEX,(?i)Telegram,ğŸ“² Telegram
  #mm#- PROCESS-NAME-REGEX,(?i)microsoft,ğŸªŸ Microsoft    
  #pcï¼Œrouter
  #pr#- DOMAIN-KEYWORD, kxxx1,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx2,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx3,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx4,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx5,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx6,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx7,ğŸŒˆ PrProxy
  #pr#- DST-PORT,kxxx8,ğŸŒˆ PrProxy

  #å¹¿å‘Š
  #- RULE-SET,ads_domain,REJECT
  
  - RULE-SET,private_domain,ğŸŸ¢ ç›´è¿  
  - RULE-SET,connectivity-check,ğŸŸ¢ ç›´è¿

  - RULE-SET,ai,ğŸ¤– Ai_!cn
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  #google store
  - RULE-SET,googlestore_domain,ğŸ‡¬ è°·æ­ŒæœåŠ¡
  - RULE-SET,google_domain,ğŸ‡¬ è°·æ­ŒæœåŠ¡
  - DOMAIN,www.microsoft.com,ğŸŸ¢ ç›´è¿  
  - RULE-SET,onedrive_domain,ğŸŒˆ PrProxy 
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,microsoftcn_domain,ğŸŸ¢ ç›´è¿
  - DOMAIN,www.apple.com,ğŸŸ¢ ç›´è¿ 
  - RULE-SET,apple_domain,ğŸ Apple
  - RULE-SET,applecn_domain,ğŸŸ¢ ç›´è¿
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - RULE-SET,speedtest_domain,âœˆï¸ Speedtest
  - RULE-SET,twitter_domain,ğŸ§‹ Twitter
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  - RULE-SET,geolocation-!cn,ğŸŒˆ PrProxy
  - RULE-SET,cn_domain,ğŸ¯ å…¨çƒç›´è¿  
    
  #IPåŒ¹é…
  - RULE-SET,google_ip,ğŸ‡¬ è°·æ­ŒæœåŠ¡,no-resolve
  - RULE-SET,apple_ip,ğŸ Apple,no-resolve
  - RULE-SET,netflix_ip,ğŸ¥ NETFLIX,no-resolve
  - RULE-SET,twitter_ip,ğŸ§‹ Twitter,no-resolve
  - RULE-SET,telegram_ip,ğŸ“² Telegram,no-resolve
  - RULE-SET,private_ip,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,cloudflare_ip,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,cn_ip,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  qdomain: &qdomain {type: http, interval: 1800, behavior: domain, format: mrs}
  zdy: &zdy {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  private_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs" }  
  mdirect: { <<:  *qdomain, url: "https://ghfast.top/raw.githubusercontent.com/sztuxp/rules/main/config/Clash/mdirect.mrs" }  
  tvproxy: { <<:  *qdomain, url: "https://ghfast.top/raw.githubusercontent.com/sztuxp/rules/main/config/Clash/tvproxy.mrs" }
  googlestore_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/sztuxp/rules/main/config/Clash/googlestore.mrs" }
  connectivity-check: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/connectivity-check.mrs" }
  #ç§‹é£å»å¹¿å‘Š
  ads_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.mrs"} 
  ai: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-chat-!cn.mrs" }  
  youtube_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs" }
  google_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs" }
  github_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs" }
  twitter_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs" }
  telegram_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs" }
  netflix_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs" }
  paypal_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs" }
  onedrive_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs" }
  microsoft_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs" }
  microsoftcn_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft@cn.mrs" }
  applecn_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs" }
  apple_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs" }
  speedtest_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs" }
  tiktok_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs" }

  geolocation-!cn: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs" }
  cn_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs" }  
  private_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs" }
  cn_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs" }
  google_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs" }
  cloudflare_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cloudflare.mrs" }
  twitter_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs" }
  telegram_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs" }
  apple_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs" }
  #facebook_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs" }
  netflix_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs" }
