# é”šç‚¹
yt: &yt {type: select, proxies: [ğŸ”® èŠ‚ç‚¹å‡è¡¡,ğŸš æ²¹ç®¡èŠ‚ç‚¹, ğŸ”¯ èŠ‚ç‚¹æ•…è½¬, â™»ï¸ èŠ‚ç‚¹è‡ªåŠ¨, ğŸ§šæ‰‹åŠ¨èŠ‚ç‚¹]}
zj: &zj {type: select, include-all: true, filter: "(?i)(xxxx1)"}
zj1: &zj1 {include-all: true, filter: "(?i)(xxxx4)"}

filterUs: &filterUs {include-all: true, filter: "(?i)(xxxx2)"}
filterZJ: &filterZJ {include-all: true, filter: "^(?i)(xxxx3)"}


# è®¢é˜…ï¼Œåç§°ä¸èƒ½é‡å¤
proxy-providers:
  Airport_01:
    type: http
    interval: 14400 #4å°æ—¶ä¸€æ¬¡
    health-check:
      enable: true
      #url: http://www.msftconnecttest.com/connecttest.txt      
      #url: https://www.apple.com/library/test/success.html
      #url: https://www.qualcomm.cn/generate_204	
      #url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ğŸŸ¢ ç›´è¿
    url: https://xxxx.com  
# ç”¨äºä¸‹è½½è®¢é˜…æ—¶æŒ‡å®šUA
global-ua:
    
# å…¨å±€é…ç½®
port: 7890
socks-port: 7891
geodata-mode: true
# GEO æ–‡ä»¶åŠ è½½æ¨¡å¼ï¼ˆstandardï¼šæ ‡å‡†åŠ è½½å™¨/memconservativeï¼šä¸“ä¸ºå†…å­˜å—é™ (å°å†…å­˜) è®¾å¤‡ä¼˜åŒ–çš„åŠ è½½å™¨ (é»˜è®¤å€¼)ï¼‰
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 48
geox-url:
  geosite: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb"
  geoip: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  asn: "https://ghfast.top/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
  
# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090
secret: "123123"
external-ui: ui
external-ui-url: "https://ghfast.top/https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"

# åŒ¹é…è¿›ç¨‹ always/strict/off
find-process-mode: off
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

# ç­–ç•¥ç»„é€‰æ‹©å’Œfakeipç¼“å­˜
profile:
    - https://dns.alidns.com/dns-query     
proxies:
- name: "ğŸŸ¢ ç›´è¿"
  type: direct
  udp: true

# ğŸƒ ğŸŒˆ  ğŸ”´ğŸ•ºğŸ¿ğŸ’¸ğŸ® ğŸ‡­ğŸ‡° ğŸ‡¯ğŸ‡µ ğŸ”® ğŸš è‡ªå»º ğŸ§š ğŸ¥ ğŸ¦ ğŸ¬ ğŸ ğŸ“º ğŸ¶ ğŸ‘¨â€ğŸ’» ğŸ“¢ â“‚ï¸ âœˆï¸ ğŸ›©ï¸ ğŸ“½ï¸ ğŸ—ï¸ 
# ç­–ç•¥ç»„
proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ èŠ‚ç‚¹è‡ªåŠ¨, ğŸš è‡ªå»ºèŠ‚ç‚¹, ğŸ§šæ‰‹åŠ¨èŠ‚ç‚¹, ğŸŒ å…¨éƒ¨èŠ‚ç‚¹]}
  - {name: ğŸš æ²¹ç®¡èŠ‚ç‚¹, <<: *zj}
  - {name: ğŸ“¹ YouTube, <<: *yt}
  # é˜²æ­¢ YouTube ç­‰ä½¿ç”¨ QUIC å¯¼è‡´é€Ÿåº¦ä¸ä½³, ç¦ç”¨ 443 ç«¯å£ UDP æµé‡ï¼ˆä¸åŒ…æ‹¬å›½å†…ï¼‰
  #- AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((RULE-SET,cn_ip))),REJECT
  #- AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((RULE-SET,cn_domain))),REJECT  
  #ç¦ç”¨æ‰€æœ‰UDPæµé‡
  - AND,((AND,(DST-PORT,443),(NETWORK,UDP))),REJECT
  - DOMAIN-SUFFIX,googleapis.cn,ğŸŸ¢ ç›´è¿
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,ğŸŸ¢ ç›´è¿  
  - RULE-SET,mdirect,ğŸŸ¢ ç›´è¿
  - RULE-SET,tvproxy,ğŸ•º TvProxy
  #mobi  
  #mm#- PROCESS-NAME,app.revanced.android.gms,ğŸ“¹ YouTube
  #mm#- PROCESS-NAME,app.rvx.android.youtube,ğŸ“¹ YouTube
  #mm#- PROCESS-NAME-REGEX,(?i)google,ğŸ‡¬ è°·æ­ŒæœåŠ¡ 
  #mm#- PROCESS-NAME-REGEX,.*downloads,ğŸ‡¬ è°·æ­ŒæœåŠ¡
  #mm#- PROCESS-NAME-REGEX,(?i)Telegram,ğŸ“² Telegram
  #mm#- PROCESS-NAME-REGEX,(?i)microsoft,ğŸªŸ Microsoft    
  #pcï¼Œrouter
  #pr#- DOMAIN-KEYWORD, kxxx1,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx2,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx3,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx4,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx5,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx6,ğŸŒˆ PrProxy
  #pr#- DOMAIN-KEYWORD, kxxx7,ğŸŒˆ PrProxy
  #pr#- DST-PORT,kxxx8,ğŸŒˆ PrProxy

  #å¹¿å‘Š
  #- RULE-SET,ads_domain,REJECT
  
  - RULE-SET,private_domain,ğŸŸ¢ ç›´è¿  
  - RULE-SET,connectivity-check,ğŸŸ¢ ç›´è¿
  - RULE-SET,googlestore_domain,ğŸ‡¬ è°·æ­ŒæœåŠ¡
  - RULE-SET,google_domain,ğŸ‡¬ è°·æ­ŒæœåŠ¡
  - DOMAIN,www.microsoft.com,ğŸŸ¢ ç›´è¿  
  - RULE-SET,onedrive_domain,ğŸªŸ Microsoft 
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,microsoftcn_domain,ğŸŸ¢ ç›´è¿
  - DOMAIN,www.apple.com,ğŸŸ¢ ç›´è¿ 
  - RULE-SET,apple_domain,ğŸ Apple
  - RULE-SET,applecn_domain,ğŸŸ¢ ç›´è¿
  - RULE-SET,tiktok_domain,ğŸµ TikTok
  - RULE-SET,speedtest_domain,âœˆï¸ Speedtest
  - RULE-SET,twitter_domain,ğŸ§‹ Twitter
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,netflix_domain,ğŸ¥ NETFLIX
  - RULE-SET,paypal_domain,ğŸ’¶ PayPal
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  qdomain: &qdomain {type: http, interval: 1800, behavior: domain, format: mrs}
  zdy: &zdy {type: http, interval: 86400, behavior: domain, format: text}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  private_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs" }  
  mdirect: { <<:  *qdomain, url: "https://ghfast.top/raw.githubusercontent.com/sztuxp/rules/main/config/Clash/mdirect.mrs" }  
  tvproxy: { <<:  *qdomain, url: "https://ghfast.top/raw.githubusercontent.com/sztuxp/rules/main/config/Clash/tvproxy.mrs" }
  googlestore_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/sztuxp/rules/main/config/Clash/googlestore.mrs" }
  connectivity-check: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/connectivity-check.mrs" }
  #ç§‹é£å»å¹¿å‘Š
  ads_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.mrs"} 
  ai: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-chat-!cn.mrs" }  
  youtube_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs" }
  google_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs" }
  github_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs" }
  twitter_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs" }
  telegram_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs" }
  netflix_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs" }
  paypal_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs" }
  onedrive_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs" }
  microsoft_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs" }
  microsoftcn_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft@cn.mrs" }
  applecn_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs" }
  apple_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs" }
  speedtest_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs" }
  tiktok_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs" }

  geolocation-!cn: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs" }
  cn_domain: { <<: *domain, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs" }  
  private_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs" }
  cn_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs" }
  google_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs" }
  cloudflare_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cloudflare.mrs" }
  twitter_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs" }
  telegram_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs" }
  apple_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs" }
  #facebook_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs" }
  netflix_ip: { <<: *ip, url: "https://ghfast.top/raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs" }
